### ISSUE TITLE
Can not view problem when click link in Course's Homework

### ISSUE THREAD

**Issue by Bogay** [Normal-OJ/Front-End#16]
for example, when I click this link
![image](https://user-images.githubusercontent.com/16890663/73191249-244f5200-4162-11ea-8e7b-3eb4554ec792.png)
I get a white page instead of problem's page due to the wrong URL
got `https://noj.tw/course/Course/problem/4`, but the correct URL is `https://noj.tw/problem/4`

**Comment by Uier** [comment]
fixed after refactoring.
